Fix access for parameters
For some reason in some cases (When test controller in specs, and if use POST request) I got error `undefined method `downcase' for nil:NilClass` on line `lib/rubykassa/notification.rb:11`. After some debugging I found that in failed cases params hash have symbols in keys. And in success  cases params hash is instance of `HashWithIndifferentAccess`. So I suggest to make force converting to `HashWithIndifferentAccess`.